# Generated by Django 3.0.6 on 2020-06-03 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_15m_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_15m_prev', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_15m_change', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_15m_per', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_30m_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_30m_prev', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_30m_change', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_30m_per', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_60m_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_60m_prev', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_60m_change', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_60m_per', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_90m_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_90m_prev', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_90m_change', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_90m_per', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_1h_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_1h_prev', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_1h_change', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_1h_per', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_1d_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_1d_prev', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_1d_change', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_1d_per', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_5d_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_5d_prev', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_5d_change', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_5d_per', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_1w_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_1w_prev', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_1w_change', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_1w_per', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_1mo_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_1mo_prev', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_1mo_change', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_1mo_per', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_3mo_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_3mo_prev', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_3mo_change', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_3mo_per', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_6mo_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_6mo_prev', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_6mo_change', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_6mo_per', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_1y_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_1y_prev', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_1y_change', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_1y_per', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_2y_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_2y_prev', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_2y_change', models.DecimalField(decimal_places=4, max_digits=10)),
                ('l_2y_per', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Currency')),
            ],
        ),
    ]
